
name: Lighthouse Check
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  lighthouse-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set up Node.js (npm)
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install Gulp as Global Package
      shell: powershell
      run: npm install -g gulp

    - name: Restore packages, build, and run Web Server in the background
      run: |
        cd ComplaintTracking
        npm install
        gulp
        dotnet restore
        dotnet build
        dotnet run &
    
    - name: Create temporary folder for artifacts storage
      shell: powershell
      run: mkdir ./tmp/lighthouse-artifacts

    - name: Installing Lighthouse through NPM
      shell: powershell
      run: npm install -g @foo-software/lighthouse-check
      
    - name: Run Lighthouse Check
      shell: powershell
      run: |
        lighthouse-check \
        --verbose \
        --prCommentEnabled \
        --emulatedFormFactor "all" \
        --prCommentAccessToken "${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}" \
        --prCommentUrl "https://api.github.com/repos/gaepdit/template-app/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')/reviews" \
        --timeout "5" \
        --overridesJsonFile ".github/workflows/lighthouse-config.json" \
        --urls "https://localhost:44312" \
        --outputDirectory /tmp/lighthouse-artifacts
    
    - name: Handle Lighthouse Check results
      shell: powershell
      run: |
        lighthouse-check-status --outputDirectory /tmp/lighthouse-artifacts \
        --minAccessibilityScore 40 \
        --minBestPracticesScore 40 \
        --minPerformanceScore 40 \
        --minSeoScore 40

    