
name: Lighthouse Check
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  lighthouse-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set up Node.js (npm)
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install Gulp as Global Package
      shell: powershell
      run: npm install -g gulp

    - name: Restore packages, build, and run Web Server in the background
      run: |
        cd ComplaintTracking
        npm install
        gulp
        dotnet restore
        dotnet build
        dotnet run &
    
    - name: Create temporary folder for artifacts storage
      run: curl https://localhost:44312
    